import { redirect } from 'next/navigation';
import "./globals.css";

export const metadata = {
  title: "Phat Next App",
  description: "Generated by create next app, by also by Phat tho",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link href="/src/styles.css" rel="stylesheet" />
    </head>
    <body
    className={`antialiased`}
    >
        <div>
            <h1 className="blue">Root Layout</h1>
            <main>{children}</main>
        </div>
    </body>
</html>
  )
}
