import { redirect } from 'next/navigation';
import "./globals.css";

export const metadata = {
  title: "Phat Next App",
  description: "Generated by create next app, by also by Phat tho",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='w-full h-full'>
    <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    </head>
    <body
    className="w-full h-full"
    >
      <main
      className="w-full h-full"
      >
        {children}
      </main>
    </body>
</html>
  )
}
